require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'APTest' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'UTDID'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod "Qiniu", "~> 8.3.2"
  pod 'NewRelicAgent'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'JPush', :path => '../node_modules/jpush-react-native'
  pod 'JCore', :path => '../node_modules/jcore-react-native'

  pod 'MixpanelReactNative', :path => '../node_modules/mixpanel-react-native'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  target 'APTestTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!({ 'Flipper-Folly' => '2.6.7' })
  #use_flipper!({ 'Flipper' => '0.95.0' })
  #use_flipper!
  post_install do |installer|
#    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end

target 'APTest-tvOS' do
  # Pods for APTest-tvOS

  target 'APTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
