# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
      ENV["SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER"] = "665"
      ENV["FASTLANE_USER"] = "dingzhigang@cainiaomeishi.com"
      ENV["FASTLANE_PASSWORD"] = "Hwcnc1019"
      ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "rcyf-hmko-mewi-rfni"
    increment_build_number(xcodeproj: "APTest.xcodeproj")
    build_app(workspace: "APTest.xcworkspace", scheme: "APTest")
    upload_to_testflight
  end
end
