import keyMirror from 'key-mirror'

export default keyMirror({
  SET_PLATFORM: null,
  SET_VERSION: null,

  SESSION_TOKEN_REQUEST: null,
  SESSION_TOKEN_SUCCESS: null,
  SESSION_TOKEN_FAILURE: null,
  LOGIN_PROFILE_SUCCESS: null,
  CHECK_VERSION_AT: null,

  SET_CURR_PROFILE: null,
  SET_CURR_STORE: null,
  UPDATE_CFG: null,
  UPDATE_CFG_ITEM: null,
  HOST_UPDATED: null,
  UPDATE_EDIT_PRODUCT_STORE_ID: null,

  DELETE_TOKEN_REQUEST: null,
  DELETE_TOKEN_SUCCESS: null,

  ON_LOGIN_STATE_CHANGE: null,
  LOGOUT: null,

  ON_AUTH_FORM_FIELD_CHANGE: null,
  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  LOGGED_IN: null,
  LOGGED_OUT: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,

  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  PROFILE_UPDATE_REQUEST: null,
  PROFILE_UPDATE_SUCCESS: null,
  PROFILE_UPDATE_FAILURE: null,

  GET_ORDER_REQUEST: null,
  GET_ORDER_SUCCESS: null,
  GET_ORDER_FAILURE: null,


  ORDER_UPDATE_REQUEST: null,
  ORDER_UPDATE_SUCCESS: null,
  ORDER_UPDATE_FAILURE: null,
  ORDER_PRINTED_CLOUD: null,
  ORDER_ADD_ITEM: null,
  ORDER_EDIT_ITEM: null,
  ORDER_INVALIDATED: null,
  ORDER_WAY_ROCED: null,

  FORGOT_PASSWORD: null,
  LOGIN: null,
  REGISTER: null,

  GET_USER_COUNT: null,
  GET_WORKER: null,
  GET_VENDOR_STORES: null,
  GET_STORE_TURNOVER: null,
  GET_WM_STORES: null,
  GET_VENDOR_DUTY_USERS:null,

  GET_CONTACT_REQUEST: null,
  GET_CONTACT_SUCCESS: null,
  GET_CONTACT_FAILURE: null,

  GET_USER_INFO: null,

  GET_NAME_PRICES: null,

  GET_PRODUCT_DETAIL: null,

  GET_PACK_WORKERS: null,
  GET_SHIP_WORKERS: null,

  GET_VENDOR_TAGS: null,
  
  GET_USER_WAGE_DATA: null,

  ACTIVITY_COMMON_RULE: null,
  ACTIVITY_SPECIAL_RULE: null,
  ACTIVITY_EXT_STORE_ID: null,
  ACTIVITY_STORE_LIST: null,
  ACTIVITY_VENDOR_TAGS: null,
  ACTIVITY_GOODS_LIST: null,
  GET_MANAGE_SELECT: null,
  ACTIVITY_MANAGER_REFRESH: null,
})
