import keyMirror from 'key-mirror'

export default keyMirror({
    SET_PLATFORM: null,
    SET_VERSION: null,

    SESSION_TOKEN_REQUEST: null,
    SESSION_TOKEN_SUCCESS: null,
    SESSION_TOKEN_FAILURE: null,
    LOGIN_PROFILE_SUCCESS: null,

    SET_CURR_STORE: null,
    UPDATE_CFG: null,

    DELETE_TOKEN_REQUEST: null,
    DELETE_TOKEN_SUCCESS: null,

    ON_LOGIN_STATE_CHANGE: null,
    LOGOUT: null,

    ON_AUTH_FORM_FIELD_CHANGE: null,
    SIGNUP_REQUEST: null,
    SIGNUP_SUCCESS: null,
    SIGNUP_FAILURE: null,

    LOGIN_REQUEST: null,
    LOGIN_SUCCESS: null,
    LOGIN_FAILURE: null,

    LOGOUT_REQUEST: null,
    LOGOUT_SUCCESS: null,
    LOGOUT_FAILURE: null,

    LOGGED_IN: null,
    LOGGED_OUT: null,

    RESET_PASSWORD_REQUEST: null,
    RESET_PASSWORD_SUCCESS: null,
    RESET_PASSWORD_FAILURE: null,

    GET_PROFILE_REQUEST: null,
    GET_PROFILE_SUCCESS: null,
    GET_PROFILE_FAILURE: null,

    ON_PROFILE_FORM_FIELD_CHANGE: null,

    PROFILE_UPDATE_REQUEST: null,
    PROFILE_UPDATE_SUCCESS: null,
    PROFILE_UPDATE_FAILURE: null,

    GET_ORDER_REQUEST: null,
    GET_ORDER_SUCCESS: null,
    GET_ORDER_FAILURE: null,

    ORDER_UPDATE_REQUEST: null,
    ORDER_UPDATE_SUCCESS: null,
    ORDER_UPDATE_FAILURE: null,
  ORDER_PRINTED_CLOUD: null,

    FORGOT_PASSWORD: null,
    LOGIN: null,
    REGISTER: null,

    GET_USER_COUNT: null,

  GET_CONTACT_REQUEST: null,
  GET_CONTACT_SUCCESS: null,
  GET_CONTACT_FAILURE: null,

})
