import keyMirror from 'key-mirror'

export default keyMirror({
  FETCH_UNLOCKED_REQ: null,
  FETCH_LOCKED_REQ: null,
  EDIT_UNLOCKED_REQ_ITEMS: null,
  EDIT_UNLOCKED_REQ: null,
  LOCK_PROVIDE_REQ: null,
  LIST_ALL_SUPPLIERS: null,
  AFTER_SET_REQ_SUPPLIER: null,
  AFTER_CREATE_SUPPLY_ORDER: null,
  RECEIVE_WAIT_SUPPLY_ORDER: null,
  RECEIVE_RECEIVED_SUPPLY_ORDER: null,
  RECEIVE_WAIT_BALANCE_SUPPLY_ORDER: null,
  RECEIVE_BALANCED_SUPPLY_ORDER: null,
  AFTER_UPDATE_SUPPLY_ORDER: null,
  AFTER_UPDATE_SUPPLY_ORDER_ITEM: null,
  AFTER_DELETE_SUPPLY_ORDER_ITEM: null,
  AFTER_TRANSFER_ORDER_ITEM: null,
  AFTER_APPEND_SUPPLY_ORDER: null,
  REMOVE_SUPPLY_ORDER: null
})
