'use strict';

export const FETCH_REMIND_LIST = 'FETCH_REMIND_LIST';
export const FETCH_REMIND_COUNT = 'FETCH_REMIND_COUNT';
export const RECEIVE_REMIND_COUNT = 'RECEIVE_REMIND_COUNT';
export const RECEIVE_REMIND_LIST = 'RECEIVE_REMIND_LIST';
export const UPDATE_REMIND_STATUS = 'UPDATE_REMIND_STATUS';
export const UPDATE_REMIND_STATUS_SUCCESS = 'UPDATE_REMIND_STATUS_SUCCESS';
